### ISSUE TITLE
Running on Anaconda Powershell Error code

### ISSUE THREAD

**Issue by SpeciesXBeer** [rbbrdckybk/ai-art-generator#17]
I am attempting to run this on Anaconda Powershell, so maybe this is my first mistake, but everything was installing and running smoothly up until putting in the curl prompts under "6] Download the default VQGAN pre-trained model checkpoint files:" step.

I am getting the following error, immediately after the input **"curl -L -o checkpoints/vqgan_imagenet_f16_16384.yaml -C - "https://heibox.uni-heidelberg.de/d/a7530b09fed84f80a887/files/?p=%2Fconfigs%2Fmodel.yaml&dl=1"** :

Invoke-WebRequest : Parameter cannot be processed because the parameter name 'C' is ambiguous. Possible matches         include: -Credential -CertificateThumbprint -Certificate -ContentType.                                                  At line:1 char:54                                                                                                       + curl -L -o checkpoints/vqgan_imagenet_f16_16384.yaml -C - "https://he ...                                             +                                                      ~~                                                                   + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException                           + FullyQualifiedErrorId : AmbiguousParameter,Microsoft.PowerShell.Commands.InvokeWebRequestCommand 

Thanks in advance!

**Comment by salva133** [comment]
I second that

**Comment by rbbrdckybk** [comment]
Not sure what the issue is, but if curl isn't working properly in your environment you can always download the files via some other method (e.g. any web brower - just point it at the URL specified by the -C parameter, in this case **https://heibox.uni-heidelberg.de/d/a7530b09fed84f80a887/files/?p=%2Fconfigs%2Fmodel.yaml&dl=1**). Then just rename the downloaded file and put it where it needs to be according to the curl command (e.g. in this case, the downloaded file should be named **vqgan_imagenet_f16_16384.yaml** and placed in  the **checkpoints** directory).
